/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2025-05-21 06:00:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class DoctorBySpecialization_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/saurabhkumarg/javaTraining/Day28/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hms/WEB-INF/lib/jsf-impl-2.2.14.jar!/META-INF/html_basic.tld", Long.valueOf(1479140598000L));
    _jspx_dependants.put("/WEB-INF/lib/jsf-impl-2.2.14.jar", Long.valueOf(1747199510929L));
    _jspx_dependants.put("jar:file:/C:/Users/saurabhkumarg/javaTraining/Day28/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hms/WEB-INF/lib/jsf-impl-2.2.14.jar!/META-INF/jsf_core.tld", Long.valueOf(1479140578000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005fview;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fform;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fselectOneMenu_0026_005fvalueChangeListener_005fvalue_005fonchange_005fid;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005fselectItems_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005foutputLabel_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fdataTable_0026_005fvar_005fvalue_005fborder;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fcolumn;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ff_005fview = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fform = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fselectOneMenu_0026_005fvalueChangeListener_005fvalue_005fonchange_005fid = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ff_005fselectItems_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005foutputLabel_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fdataTable_0026_005fvar_005fvalue_005fborder = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fcolumn = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ff_005fview.release();
    _005fjspx_005ftagPool_005fh_005fform.release();
    _005fjspx_005ftagPool_005fh_005fselectOneMenu_0026_005fvalueChangeListener_005fvalue_005fonchange_005fid.release();
    _005fjspx_005ftagPool_005ff_005fselectItems_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fh_005foutputLabel_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fh_005fdataTable_0026_005fvar_005fvalue_005fborder.release();
    _005fjspx_005ftagPool_005fh_005fcolumn.release();
    _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      if (_jspx_meth_f_005fview_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_f_005fview_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  f:view
    com.sun.faces.taglib.jsf_core.ViewTag _jspx_th_f_005fview_005f0 = new com.sun.faces.taglib.jsf_core.ViewTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_f_005fview_005f0);
    try {
      _jspx_th_f_005fview_005f0.setPageContext(_jspx_page_context);
      _jspx_th_f_005fview_005f0.setParent(null);
      _jspx_th_f_005fview_005f0.setJspId("jsp_1228615492_0");
      int _jspx_eval_f_005fview_005f0 = _jspx_th_f_005fview_005f0.doStartTag();
      if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_f_005fview_005f0);
        }
        do {
          out.write("\r\n");
          out.write("<html>\r\n");
          out.write("    <head>\r\n");
          out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
          out.write("        <title>Doctors by Specialization</title>\r\n");
          out.write("        \r\n");
          out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/css/DoctorBy.css\">\r\n");
          out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/css/navbar.css\">\r\n");
          out.write("        \r\n");
          out.write("        \r\n");
          out.write("    </head>\r\n");
          out.write("    <body>\r\n");
          out.write("        ");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "NavBar.jsp", out, false);
          out.write("\r\n");
          out.write("\r\n");
          out.write("        ");
          if (_jspx_meth_h_005fform_005f0(_jspx_th_f_005fview_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("    </body>\r\n");
          out.write("</html>\r\n");
          int evalDoAfterBody = _jspx_th_f_005fview_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_f_005fview_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005fview_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fform_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:form
    com.sun.faces.taglib.html_basic.FormTag _jspx_th_h_005fform_005f0 = new com.sun.faces.taglib.html_basic.FormTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fform_005f0);
    try {
      _jspx_th_h_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005fform_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fview_005f0);
      _jspx_th_h_005fform_005f0.setJspId("jsp_1228615492_1");
      int _jspx_eval_h_005fform_005f0 = _jspx_th_h_005fform_005f0.doStartTag();
      if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005fform_005f0);
        }
        do {
          out.write("\r\n");
          out.write("        <br>\r\n");
          out.write("            <!-- Dropdown to select Specialization -->\r\n");
          out.write("            ");
          if (_jspx_meth_h_005fselectOneMenu_005f0(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            \r\n");
          out.write("            <br/><br/>\r\n");
          out.write("            <br>\r\n");
          out.write("           <b> ");
          if (_jspx_meth_h_005foutputLabel_005f0(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write(" </b> <br>\r\n");
          out.write("            ");
          if (_jspx_meth_h_005foutputText_005f0(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("<br>\r\n");
          out.write("            <!-- Table of doctors filtered by specialization -->\r\n");
          out.write("            ");
          if (_jspx_meth_h_005fdataTable_005f0(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_h_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fform_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fselectOneMenu_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:selectOneMenu
    com.sun.faces.taglib.html_basic.SelectOneMenuTag _jspx_th_h_005fselectOneMenu_005f0 = new com.sun.faces.taglib.html_basic.SelectOneMenuTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fselectOneMenu_005f0);
    try {
      _jspx_th_h_005fselectOneMenu_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005fselectOneMenu_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /DoctorBySpecialization.jsp(24,12) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_h_005fselectOneMenu_005f0.setId("specialization");
      // /DoctorBySpecialization.jsp(24,12) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005fselectOneMenu_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/DoctorBySpecialization.jsp(24,12) '#{doctorDao.localCategory}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{doctorDao.localCategory}",java.lang.Object.class)));
      // /DoctorBySpecialization.jsp(24,12) name = onchange type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005fselectOneMenu_005f0.setOnchange(new org.apache.jasper.el.JspValueExpression("/DoctorBySpecialization.jsp(24,12) 'submit()'",_jsp_getExpressionFactory().createValueExpression("submit()",java.lang.String.class)));
      // /DoctorBySpecialization.jsp(24,12) name = valueChangeListener type = javax.el.MethodExpression reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = true methodSignature = void valueChange(javax.faces.event.ValueChangeEvent)
      _jspx_th_h_005fselectOneMenu_005f0.setValueChangeListener(new org.apache.jasper.el.JspMethodExpression("/DoctorBySpecialization.jsp(24,12) '#{doctorDao.doctorCategoryChanged}'",_jsp_getExpressionFactory().createMethodExpression(_jspx_page_context.getELContext(),"#{doctorDao.doctorCategoryChanged}",java.lang.Void.TYPE,new java.lang.Class[] {javax.faces.event.ValueChangeEvent.class})));
      _jspx_th_h_005fselectOneMenu_005f0.setJspId("jsp_1228615492_2");
      int _jspx_eval_h_005fselectOneMenu_005f0 = _jspx_th_h_005fselectOneMenu_005f0.doStartTag();
      if (_jspx_eval_h_005fselectOneMenu_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005fselectOneMenu_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005fselectOneMenu_005f0);
        }
        do {
          out.write("\r\n");
          out.write("                ");
          if (_jspx_meth_f_005fselectItems_005f0(_jspx_th_h_005fselectOneMenu_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_h_005fselectOneMenu_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005fselectOneMenu_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005fselectOneMenu_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fselectOneMenu_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_f_005fselectItems_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fselectOneMenu_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:selectItems
    com.sun.faces.taglib.jsf_core.SelectItemsTag _jspx_th_f_005fselectItems_005f0 = new com.sun.faces.taglib.jsf_core.SelectItemsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_f_005fselectItems_005f0);
    try {
      _jspx_th_f_005fselectItems_005f0.setPageContext(_jspx_page_context);
      _jspx_th_f_005fselectItems_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fselectOneMenu_005f0);
      // /DoctorBySpecialization.jsp(26,16) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_f_005fselectItems_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/DoctorBySpecialization.jsp(26,16) '#{doctorDao.specializations}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{doctorDao.specializations}",java.lang.Object.class)));
      _jspx_th_f_005fselectItems_005f0.setJspId("jsp_1228615492_3");
      int _jspx_eval_f_005fselectItems_005f0 = _jspx_th_f_005fselectItems_005f0.doStartTag();
      if (_jspx_th_f_005fselectItems_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005fselectItems_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputLabel_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputLabel
    com.sun.faces.taglib.html_basic.OutputLabelTag _jspx_th_h_005foutputLabel_005f0 = new com.sun.faces.taglib.html_basic.OutputLabelTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputLabel_005f0);
    try {
      _jspx_th_h_005foutputLabel_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputLabel_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /DoctorBySpecialization.jsp(31,15) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputLabel_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/DoctorBySpecialization.jsp(31,15) 'Selected Specialization: '",_jsp_getExpressionFactory().createValueExpression("Selected Specialization: ",java.lang.Object.class)));
      _jspx_th_h_005foutputLabel_005f0.setJspId("jsp_1228615492_4");
      int _jspx_eval_h_005foutputLabel_005f0 = _jspx_th_h_005foutputLabel_005f0.doStartTag();
      if (_jspx_th_h_005foutputLabel_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputLabel_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f0 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f0);
    try {
      _jspx_th_h_005foutputText_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /DoctorBySpecialization.jsp(32,12) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/DoctorBySpecialization.jsp(32,12) '#{doctorDao.localCategory}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{doctorDao.localCategory}",java.lang.Object.class)));
      _jspx_th_h_005foutputText_005f0.setJspId("jsp_1228615492_5");
      int _jspx_eval_h_005foutputText_005f0 = _jspx_th_h_005foutputText_005f0.doStartTag();
      if (_jspx_th_h_005foutputText_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fdataTable_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:dataTable
    com.sun.faces.taglib.html_basic.DataTableTag _jspx_th_h_005fdataTable_005f0 = new com.sun.faces.taglib.html_basic.DataTableTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fdataTable_005f0);
    try {
      _jspx_th_h_005fdataTable_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005fdataTable_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /DoctorBySpecialization.jsp(35,12) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005fdataTable_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/DoctorBySpecialization.jsp(35,12) '#{doctorController.showDoctorsBySpecialization(doctorDao.localCategory)}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{doctorController.showDoctorsBySpecialization(doctorDao.localCategory)}",java.lang.Object.class)));
      // /DoctorBySpecialization.jsp(35,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_h_005fdataTable_005f0.setVar("doc");
      // /DoctorBySpecialization.jsp(35,12) name = border type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = int deferredMethod = false methodSignature = null
      _jspx_th_h_005fdataTable_005f0.setBorder(new org.apache.jasper.el.JspValueExpression("/DoctorBySpecialization.jsp(35,12) '2'",_jsp_getExpressionFactory().createValueExpression("2",int.class)));
      _jspx_th_h_005fdataTable_005f0.setJspId("jsp_1228615492_6");
      int _jspx_eval_h_005fdataTable_005f0 = _jspx_th_h_005fdataTable_005f0.doStartTag();
      if (_jspx_eval_h_005fdataTable_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005fdataTable_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005fdataTable_005f0);
        }
        do {
          out.write("\r\n");
          out.write("                \r\n");
          out.write("                ");
          if (_jspx_meth_h_005fcolumn_005f0(_jspx_th_h_005fdataTable_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                \r\n");
          out.write("                ");
          if (_jspx_meth_h_005fcolumn_005f1(_jspx_th_h_005fdataTable_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                \r\n");
          out.write("                ");
          if (_jspx_meth_h_005fcolumn_005f2(_jspx_th_h_005fdataTable_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                \r\n");
          out.write("                ");
          if (_jspx_meth_h_005fcolumn_005f3(_jspx_th_h_005fdataTable_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("                ");
          if (_jspx_meth_h_005fcolumn_005f4(_jspx_th_h_005fdataTable_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_h_005fdataTable_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005fdataTable_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005fdataTable_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fdataTable_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fcolumn_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fdataTable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:column
    com.sun.faces.taglib.html_basic.ColumnTag _jspx_th_h_005fcolumn_005f0 = new com.sun.faces.taglib.html_basic.ColumnTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fcolumn_005f0);
    try {
      _jspx_th_h_005fcolumn_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005fcolumn_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fdataTable_005f0);
      _jspx_th_h_005fcolumn_005f0.setJspId("jsp_1228615492_7");
      int _jspx_eval_h_005fcolumn_005f0 = _jspx_th_h_005fcolumn_005f0.doStartTag();
      if (_jspx_eval_h_005fcolumn_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005fcolumn_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005fcolumn_005f0);
        }
        do {
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_f_005ffacet_005f0(_jspx_th_h_005fcolumn_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_h_005foutputText_005f2(_jspx_th_h_005fcolumn_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_h_005fcolumn_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005fcolumn_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005fcolumn_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fcolumn_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_f_005ffacet_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:facet
    javax.faces.webapp.FacetTag _jspx_th_f_005ffacet_005f0 = (javax.faces.webapp.FacetTag) _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.get(javax.faces.webapp.FacetTag.class);
    boolean _jspx_th_f_005ffacet_005f0_reused = false;
    try {
      _jspx_th_f_005ffacet_005f0.setPageContext(_jspx_page_context);
      _jspx_th_f_005ffacet_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f0);
      // /DoctorBySpecialization.jsp(39,20) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_f_005ffacet_005f0.setName("header");
      int _jspx_eval_f_005ffacet_005f0 = _jspx_th_f_005ffacet_005f0.doStartTag();
      if (_jspx_eval_f_005ffacet_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          if (_jspx_meth_h_005foutputText_005f1(_jspx_th_f_005ffacet_005f0, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_f_005ffacet_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_f_005ffacet_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.reuse(_jspx_th_f_005ffacet_005f0);
      _jspx_th_f_005ffacet_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005ffacet_005f0, _jsp_getInstanceManager(), _jspx_th_f_005ffacet_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005ffacet_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f1 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f1);
    try {
      _jspx_th_h_005foutputText_005f1.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005ffacet_005f0);
      // /DoctorBySpecialization.jsp(39,43) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/DoctorBySpecialization.jsp(39,43) 'Doctor ID'",_jsp_getExpressionFactory().createValueExpression("Doctor ID",java.lang.Object.class)));
      _jspx_th_h_005foutputText_005f1.setJspId("jsp_1228615492_8");
      int _jspx_eval_h_005foutputText_005f1 = _jspx_th_h_005foutputText_005f1.doStartTag();
      if (_jspx_th_h_005foutputText_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f1, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f2 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f2);
    try {
      _jspx_th_h_005foutputText_005f2.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f0);
      // /DoctorBySpecialization.jsp(40,20) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/DoctorBySpecialization.jsp(40,20) '#{doc.doctorId}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{doc.doctorId}",java.lang.Object.class)));
      _jspx_th_h_005foutputText_005f2.setJspId("jsp_1228615492_9");
      int _jspx_eval_h_005foutputText_005f2 = _jspx_th_h_005foutputText_005f2.doStartTag();
      if (_jspx_th_h_005foutputText_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f2, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fcolumn_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fdataTable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:column
    com.sun.faces.taglib.html_basic.ColumnTag _jspx_th_h_005fcolumn_005f1 = new com.sun.faces.taglib.html_basic.ColumnTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fcolumn_005f1);
    try {
      _jspx_th_h_005fcolumn_005f1.setPageContext(_jspx_page_context);
      _jspx_th_h_005fcolumn_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fdataTable_005f0);
      _jspx_th_h_005fcolumn_005f1.setJspId("jsp_1228615492_10");
      int _jspx_eval_h_005fcolumn_005f1 = _jspx_th_h_005fcolumn_005f1.doStartTag();
      if (_jspx_eval_h_005fcolumn_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005fcolumn_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005fcolumn_005f1);
        }
        do {
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_f_005ffacet_005f1(_jspx_th_h_005fcolumn_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_h_005foutputText_005f4(_jspx_th_h_005fcolumn_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_h_005fcolumn_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005fcolumn_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005fcolumn_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fcolumn_005f1, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_f_005ffacet_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:facet
    javax.faces.webapp.FacetTag _jspx_th_f_005ffacet_005f1 = (javax.faces.webapp.FacetTag) _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.get(javax.faces.webapp.FacetTag.class);
    boolean _jspx_th_f_005ffacet_005f1_reused = false;
    try {
      _jspx_th_f_005ffacet_005f1.setPageContext(_jspx_page_context);
      _jspx_th_f_005ffacet_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f1);
      // /DoctorBySpecialization.jsp(44,20) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_f_005ffacet_005f1.setName("header");
      int _jspx_eval_f_005ffacet_005f1 = _jspx_th_f_005ffacet_005f1.doStartTag();
      if (_jspx_eval_f_005ffacet_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          if (_jspx_meth_h_005foutputText_005f3(_jspx_th_f_005ffacet_005f1, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_f_005ffacet_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_f_005ffacet_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.reuse(_jspx_th_f_005ffacet_005f1);
      _jspx_th_f_005ffacet_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005ffacet_005f1, _jsp_getInstanceManager(), _jspx_th_f_005ffacet_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005ffacet_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f3 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f3);
    try {
      _jspx_th_h_005foutputText_005f3.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005ffacet_005f1);
      // /DoctorBySpecialization.jsp(44,43) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/DoctorBySpecialization.jsp(44,43) 'Name'",_jsp_getExpressionFactory().createValueExpression("Name",java.lang.Object.class)));
      _jspx_th_h_005foutputText_005f3.setJspId("jsp_1228615492_11");
      int _jspx_eval_h_005foutputText_005f3 = _jspx_th_h_005foutputText_005f3.doStartTag();
      if (_jspx_th_h_005foutputText_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f3, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f4 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f4);
    try {
      _jspx_th_h_005foutputText_005f4.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f1);
      // /DoctorBySpecialization.jsp(45,20) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f4.setValue(new org.apache.jasper.el.JspValueExpression("/DoctorBySpecialization.jsp(45,20) '#{doc.doctorName}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{doc.doctorName}",java.lang.Object.class)));
      _jspx_th_h_005foutputText_005f4.setJspId("jsp_1228615492_12");
      int _jspx_eval_h_005foutputText_005f4 = _jspx_th_h_005foutputText_005f4.doStartTag();
      if (_jspx_th_h_005foutputText_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f4, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fcolumn_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fdataTable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:column
    com.sun.faces.taglib.html_basic.ColumnTag _jspx_th_h_005fcolumn_005f2 = new com.sun.faces.taglib.html_basic.ColumnTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fcolumn_005f2);
    try {
      _jspx_th_h_005fcolumn_005f2.setPageContext(_jspx_page_context);
      _jspx_th_h_005fcolumn_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fdataTable_005f0);
      _jspx_th_h_005fcolumn_005f2.setJspId("jsp_1228615492_13");
      int _jspx_eval_h_005fcolumn_005f2 = _jspx_th_h_005fcolumn_005f2.doStartTag();
      if (_jspx_eval_h_005fcolumn_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005fcolumn_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005fcolumn_005f2);
        }
        do {
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_f_005ffacet_005f2(_jspx_th_h_005fcolumn_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_h_005foutputText_005f6(_jspx_th_h_005fcolumn_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_h_005fcolumn_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005fcolumn_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005fcolumn_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fcolumn_005f2, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_f_005ffacet_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:facet
    javax.faces.webapp.FacetTag _jspx_th_f_005ffacet_005f2 = (javax.faces.webapp.FacetTag) _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.get(javax.faces.webapp.FacetTag.class);
    boolean _jspx_th_f_005ffacet_005f2_reused = false;
    try {
      _jspx_th_f_005ffacet_005f2.setPageContext(_jspx_page_context);
      _jspx_th_f_005ffacet_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f2);
      // /DoctorBySpecialization.jsp(49,20) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_f_005ffacet_005f2.setName("header");
      int _jspx_eval_f_005ffacet_005f2 = _jspx_th_f_005ffacet_005f2.doStartTag();
      if (_jspx_eval_f_005ffacet_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          if (_jspx_meth_h_005foutputText_005f5(_jspx_th_f_005ffacet_005f2, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_f_005ffacet_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_f_005ffacet_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.reuse(_jspx_th_f_005ffacet_005f2);
      _jspx_th_f_005ffacet_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005ffacet_005f2, _jsp_getInstanceManager(), _jspx_th_f_005ffacet_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005ffacet_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f5 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f5);
    try {
      _jspx_th_h_005foutputText_005f5.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005ffacet_005f2);
      // /DoctorBySpecialization.jsp(49,43) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f5.setValue(new org.apache.jasper.el.JspValueExpression("/DoctorBySpecialization.jsp(49,43) 'Specialization'",_jsp_getExpressionFactory().createValueExpression("Specialization",java.lang.Object.class)));
      _jspx_th_h_005foutputText_005f5.setJspId("jsp_1228615492_14");
      int _jspx_eval_h_005foutputText_005f5 = _jspx_th_h_005foutputText_005f5.doStartTag();
      if (_jspx_th_h_005foutputText_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f5, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f6 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f6);
    try {
      _jspx_th_h_005foutputText_005f6.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f2);
      // /DoctorBySpecialization.jsp(50,20) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f6.setValue(new org.apache.jasper.el.JspValueExpression("/DoctorBySpecialization.jsp(50,20) '#{doc.specialization}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{doc.specialization}",java.lang.Object.class)));
      _jspx_th_h_005foutputText_005f6.setJspId("jsp_1228615492_15");
      int _jspx_eval_h_005foutputText_005f6 = _jspx_th_h_005foutputText_005f6.doStartTag();
      if (_jspx_th_h_005foutputText_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f6, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fcolumn_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fdataTable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:column
    com.sun.faces.taglib.html_basic.ColumnTag _jspx_th_h_005fcolumn_005f3 = new com.sun.faces.taglib.html_basic.ColumnTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fcolumn_005f3);
    try {
      _jspx_th_h_005fcolumn_005f3.setPageContext(_jspx_page_context);
      _jspx_th_h_005fcolumn_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fdataTable_005f0);
      _jspx_th_h_005fcolumn_005f3.setJspId("jsp_1228615492_16");
      int _jspx_eval_h_005fcolumn_005f3 = _jspx_th_h_005fcolumn_005f3.doStartTag();
      if (_jspx_eval_h_005fcolumn_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005fcolumn_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005fcolumn_005f3);
        }
        do {
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_f_005ffacet_005f3(_jspx_th_h_005fcolumn_005f3, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_h_005foutputText_005f8(_jspx_th_h_005fcolumn_005f3, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_h_005fcolumn_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005fcolumn_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005fcolumn_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fcolumn_005f3, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_f_005ffacet_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:facet
    javax.faces.webapp.FacetTag _jspx_th_f_005ffacet_005f3 = (javax.faces.webapp.FacetTag) _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.get(javax.faces.webapp.FacetTag.class);
    boolean _jspx_th_f_005ffacet_005f3_reused = false;
    try {
      _jspx_th_f_005ffacet_005f3.setPageContext(_jspx_page_context);
      _jspx_th_f_005ffacet_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f3);
      // /DoctorBySpecialization.jsp(54,20) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_f_005ffacet_005f3.setName("header");
      int _jspx_eval_f_005ffacet_005f3 = _jspx_th_f_005ffacet_005f3.doStartTag();
      if (_jspx_eval_f_005ffacet_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          if (_jspx_meth_h_005foutputText_005f7(_jspx_th_f_005ffacet_005f3, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_f_005ffacet_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_f_005ffacet_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.reuse(_jspx_th_f_005ffacet_005f3);
      _jspx_th_f_005ffacet_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005ffacet_005f3, _jsp_getInstanceManager(), _jspx_th_f_005ffacet_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005ffacet_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f7 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f7);
    try {
      _jspx_th_h_005foutputText_005f7.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005ffacet_005f3);
      // /DoctorBySpecialization.jsp(54,43) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f7.setValue(new org.apache.jasper.el.JspValueExpression("/DoctorBySpecialization.jsp(54,43) 'Mobile No'",_jsp_getExpressionFactory().createValueExpression("Mobile No",java.lang.Object.class)));
      _jspx_th_h_005foutputText_005f7.setJspId("jsp_1228615492_17");
      int _jspx_eval_h_005foutputText_005f7 = _jspx_th_h_005foutputText_005f7.doStartTag();
      if (_jspx_th_h_005foutputText_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f7, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f8 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f8);
    try {
      _jspx_th_h_005foutputText_005f8.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f3);
      // /DoctorBySpecialization.jsp(55,20) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f8.setValue(new org.apache.jasper.el.JspValueExpression("/DoctorBySpecialization.jsp(55,20) '#{doc.mobileNo}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{doc.mobileNo}",java.lang.Object.class)));
      _jspx_th_h_005foutputText_005f8.setJspId("jsp_1228615492_18");
      int _jspx_eval_h_005foutputText_005f8 = _jspx_th_h_005foutputText_005f8.doStartTag();
      if (_jspx_th_h_005foutputText_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f8, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fcolumn_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fdataTable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:column
    com.sun.faces.taglib.html_basic.ColumnTag _jspx_th_h_005fcolumn_005f4 = new com.sun.faces.taglib.html_basic.ColumnTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fcolumn_005f4);
    try {
      _jspx_th_h_005fcolumn_005f4.setPageContext(_jspx_page_context);
      _jspx_th_h_005fcolumn_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fdataTable_005f0);
      _jspx_th_h_005fcolumn_005f4.setJspId("jsp_1228615492_19");
      int _jspx_eval_h_005fcolumn_005f4 = _jspx_th_h_005fcolumn_005f4.doStartTag();
      if (_jspx_eval_h_005fcolumn_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005fcolumn_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005fcolumn_005f4);
        }
        do {
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_f_005ffacet_005f4(_jspx_th_h_005fcolumn_005f4, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_h_005foutputText_005f10(_jspx_th_h_005fcolumn_005f4, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_h_005fcolumn_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005fcolumn_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005fcolumn_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fcolumn_005f4, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_f_005ffacet_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:facet
    javax.faces.webapp.FacetTag _jspx_th_f_005ffacet_005f4 = (javax.faces.webapp.FacetTag) _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.get(javax.faces.webapp.FacetTag.class);
    boolean _jspx_th_f_005ffacet_005f4_reused = false;
    try {
      _jspx_th_f_005ffacet_005f4.setPageContext(_jspx_page_context);
      _jspx_th_f_005ffacet_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f4);
      // /DoctorBySpecialization.jsp(59,20) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_f_005ffacet_005f4.setName("header");
      int _jspx_eval_f_005ffacet_005f4 = _jspx_th_f_005ffacet_005f4.doStartTag();
      if (_jspx_eval_f_005ffacet_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          if (_jspx_meth_h_005foutputText_005f9(_jspx_th_f_005ffacet_005f4, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_f_005ffacet_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_f_005ffacet_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.reuse(_jspx_th_f_005ffacet_005f4);
      _jspx_th_f_005ffacet_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005ffacet_005f4, _jsp_getInstanceManager(), _jspx_th_f_005ffacet_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005ffacet_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f9 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f9);
    try {
      _jspx_th_h_005foutputText_005f9.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005ffacet_005f4);
      // /DoctorBySpecialization.jsp(59,43) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f9.setValue(new org.apache.jasper.el.JspValueExpression("/DoctorBySpecialization.jsp(59,43) 'Status'",_jsp_getExpressionFactory().createValueExpression("Status",java.lang.Object.class)));
      _jspx_th_h_005foutputText_005f9.setJspId("jsp_1228615492_20");
      int _jspx_eval_h_005foutputText_005f9 = _jspx_th_h_005foutputText_005f9.doStartTag();
      if (_jspx_th_h_005foutputText_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f9, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f10 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f10);
    try {
      _jspx_th_h_005foutputText_005f10.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f4);
      // /DoctorBySpecialization.jsp(60,20) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f10.setValue(new org.apache.jasper.el.JspValueExpression("/DoctorBySpecialization.jsp(60,20) '#{doc.isStatus}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{doc.isStatus}",java.lang.Object.class)));
      _jspx_th_h_005foutputText_005f10.setJspId("jsp_1228615492_21");
      int _jspx_eval_h_005foutputText_005f10 = _jspx_th_h_005foutputText_005f10.doStartTag();
      if (_jspx_th_h_005foutputText_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f10, _jsp_getInstanceManager(), false);
    }
    return false;
  }
}
